### ISSUE TITLE
ineffectual assignments in Go code (https://goreportcard.com/report/github.com/kitabisa/moco)

### ISSUE THREAD

**Issue by dhiemaz** [kitabisa/moco#2]
https://github.com/kitabisa/moco/blob/a0895d992e8610aeb8af5e9cd4a4ee5963db77ed/trimmer.go#L17

can use declaration without assignment, the zero value for boolean datatype will be false.
`var found bool // <-- use zero value for boolean datatype which is false`

**Comment by pushm0v** [comment]
Solved in #3
